### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by brianloyal** [psipred/Merizo#1]
I'm getting this error while trying out Merizo on an amd64 instance (without a GPU):

(venv) [ec2-user@ip-172-31-39-67 Merizo]$ python predict.py -d cpu -i examples/2xdqA.pdb
Traceback (most recent call last):
  File "predict.py", line 8, in <module>
    from model.network import Merizo
  File "/home/ec2-user/Merizo/model/network.py", line 7, in <module>
    from .decoders.mask_decoder import MaskTransformer
  File "/home/ec2-user/Merizo/model/decoders/mask_decoder.py", line 5, in <module>
    from model.utils.utils import clean_domains, clean_singletons
  File "/home/ec2-user/Merizo/model/utils/utils.py", line 47, in <module>
    def get_ids(x: torch.tensor) -> tuple[torch.tensor, int]:
TypeError: 'type' object is not subscriptable

Running on Python 3.8.16 with following package versions:

Package                  Version
------------------------ ----------
cmake                    3.26.3
contourpy                1.0.7
cycler                   0.11.0
einops                   0.6.1
filelock                 3.12.0
fonttools                4.39.4
importlib-resources      5.12.0
Jinja2                   3.1.2
kiwisolver               1.4.4
lit                      16.0.5
MarkupSafe               2.1.2
matplotlib               3.7.1
mpmath                   1.3.0
natsort                  8.3.1
networkx                 3.1
numpy                    1.24.3
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
packaging                23.1
Pillow                   9.5.0
pip                      23.1.2
pyparsing                3.0.9
python-dateutil          2.8.2
rotary-embedding-torch   0.2.3
scipy                    1.10.1
setuptools               67.7.2
six                      1.16.0
sympy                    1.12
torch                    2.0.1
triton                   2.0.0
typing_extensions        4.5.0
wheel                    0.40.0
zipp                     3.15.0

**Comment by brianloyal** [comment]
Note: adding `from __future__ import annotations` to the top of the following files fixed this for me on Python 3.8:

./predict.py
./model/utils/utils.py
